### ISSUE TITLE
Allow this to work with vagrant

### ISSUE THREAD

**Issue by bugmen0t** [artoale/karma-brackets#7]
Well, simply, it should work with Vagrant quite easily, because I can forward the ports to localhost, and the the extension should be able to connect fine. The problem is that the extension requires you to start karma before you can run tests, and on my virtual machine, I just have karma running all the time automatically.

So I figure it will probably work if I am allowed to connect and run the tests, without having to start the server. Let me know what you think. This would be a life saver for me. :)

**Comment by artoale** [comment]
Definitely make sense...my only concern is the workflow, so I'll ask your opinion on that (be aware that  karma on vagrant should run with the karma-brackets plugin installed and configured as reporter).
- an option in the config allows to specify if you already have karma running
- when you click on start karma (maybe renamed), it will connect with karma-vagrant instance
- run test it's a little bit more complex, since is not handled by the adapter, a first implementation would allow only run on save based on karma-watch (or grunt/gulp/gwathever) you use in your env.

Does it make sense to you? Let me know...I'll hopefully be working on that in the next days

**Comment by bugmen0t** [comment]
Connecting to karma when you click "start karma" seems sufficient (as long as the menu option explicitly states that it's either starting or connecting to karma); you could alternatively have a separate "connect to karma" menu item instead of integrating it into the "start karma".

If possible, an auto-connect on brackets startup option might be useful too.

Thanks for your time, and for this extension. :+1:

**Comment by artoale** [comment]
OK, thanks for the suggestion and for enjoying this plugin. I'll refine the
workflow and let you know when there's some updates :) stay tuned!

On Tue, Feb 4, 2014 at 2:54 PM, bugmen0t notifications@github.com wrote:

> Connecting to karma when you click "start karma" seems sufficient (as long
> as the menu option explicitly states that it's either starting or
> connecting to karma); you could alternatively have a separate "connect to
> karma" menu item instead of integrating it into the "start karma" menu item.
> 
> If possible, an auto-connect on brackets startup option might be useful
> too.
> 
> Thanks for your time, and for this extension. [image: :+1:]
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/artoale/karma-brackets/issues/7#issuecomment-34066270
> .

## 

Alessandro Artoni

artoale.com

**Comment by artoale** [comment]
Hi @bugmen0t! it took me quite a lot of time, but I've been doing quite a lot of stuff (new job, new city :) )
I've just released v0.5.1 that should address exactly you problem...let me know if it works for you :)
